name: llamaresearcher-website

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5174:80
    networks:
      - nginxproxymanager_default

networks:
  nginxproxymanager_default:
    external: true
